name: gtest on macOS

on:
  workflow_dispatch:

jobs:
  macos-gtest:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install googletest
    - name: Configure gtest build
      run: |
        find / -name \*gtest\* 
        find / -name \*googletest\* 
        find / -name \*mock\* 
#        cmake -B build \
#        -DCMAKE_OSX_SYSROOT="" \
#        -DCMAKE_CXX_FLAGS="-I$(brew --prefix)/include" \
#        -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix)/lib" \
#        -DCMAKE_CXX_COMPILER=g++-14 \
#        -DCMAKE_VERBOSE_MAKEFILE=on
#    - name: Build
#      run: |
#        cmake --build build -j2
#    - name: Test
#      run: |
#        ctest --test-dir build
