name: gtest on macOS

on:
  workflow_dispatch:

jobs:
  macos-gtest:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install googletest
    - name: Configure gtest build
      run: |
        cmake -B build \
        -DCMAKE_CXX_COMPILER=g++-14 \
        -DCMAKE_VERBOSE_MAKEFILE=on
    - name: Build
      run: |
        cmake --build build -j2
    - name: Test
      run: |
        ctest --test-dir build
